"""Standalone PDF report generator shim for hackathon smoke tests."""

from __future__ import annotations

from dataclasses import asdict, is_dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


class ReportGenerator:
    def generate(self, data: dict[str, Any] | None = None, **kwargs: Any) -> str:
        payload: dict[str, Any] = {}
        if isinstance(data, dict):
            payload.update(data)
        elif data is not None and is_dataclass(data):
            payload.update(asdict(data))
        payload.update(kwargs)

        output_path = Path(str(payload.get("output_path") or f"reports/agent/meta_verdax_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"))
        output_path.parent.mkdir(parents=True, exist_ok=True)

        c = canvas.Canvas(str(output_path), pagesize=letter)
        width, height = letter
        y = height - 60

        c.setTitle("MetaVerdax Audit Report")
        c.setFont("Helvetica-Bold", 20)
        c.setFillColor(colors.HexColor("#00E5FF"))
        c.drawString(54, y, "MetaVerdax Audit Report")
        y -= 24

        c.setFont("Helvetica", 10)
        c.setFillColor(colors.black)
        for key in [
            "company_name", "dataset", "risk_level", "drift_score", "anomalies",
            "carbon_saved_kg", "timestamp", "start_date", "end_date",
        ]:
            if key in payload and payload[key] is not None:
                c.drawString(54, y, f"{key.replace('_', ' ').title()}: {payload[key]}")
                y -= 14

        c.drawString(54, y - 4, "Generated by MetaVerdax Agent")
        c.setStrokeColor(colors.HexColor("#00E5FF"))
        c.line(54, y - 10, width - 54, y - 10)
        c.showPage()
        c.save()
        return str(output_path)